server:
  port: 9999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/ws/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
